hydra:
  run:
    dir: ./outputs/lgbm/${now:%Y%m%d_%H%M%S}
current_time: ${now:%Y%m%d_%H%M%S}
feature_names:
  - goal
  - label_encode
  - count_encode
  # - by_country
  # - by_category1
  # - by_category2
  # - html_tag_all_count
  # - bins
  # - goal_cross_duration
  # - raw_text_features
  # - remove_html_text_features
  # - diff_text_features
  # - raw_tfidf_sdv64
  # - removed_html_tags_tfidf_sdv64
  # - only_text_tfidf_sdv64
  # - aggregation_country
  # - aggregation_category1
  # - aggregation_category2
  # - bert_vec
  # - bert_svd_64_vec
  # - html_bert_vec
  # - html_bert_svd_64_vec
  # - bert_reduce_max_vec
  # - raw_tfidf_sdv32
  # - removed_html_tags_tfidf_sdv32
  # - only_text_tfidf_sdv32
drop_cols:
 - index
 - id
 - goal
 - html_content
 - country
 - category1
 - category2
category_cols:
  - LE_country
  - LE_category1
  - LE_category2
  - LE_country-category1
  - LE_country-category2
  - LE_category1-category2
  - LE_country-category1-category2
  - LE_bins_duration
  - LE_bins_goal
  - LE_bins_duration-bins_goal
target_col: state
model:
  params:
    n_estimators: 5000
    objective: binary
    boosting_type: gbdt
    # metric: custom
    importance_type: gain
    num_leaves: 31
    subsample: 1
    colsample_bytree: 1
    learning_rate: 0.01
    n_jobs: -1
    verbose: -1
    random_state: 0
    min_data_in_leaf: 40
    reg_lambda: 5
  fit_params:
    early_stopping_rounds: 500
    verbose: 100
is_test: false
seed: 42