models:
  name: lgbm
  params:
    n_estimators: 5000
    objective: binary
    boosting_type: gbdt
    # metric: custom
    importance_type: gain
    num_leaves: 31
    subsample: 1
    colsample_bytree: 1
    learning_rate: 0.01
    n_jobs: -1
    verbose: -1
    random_state: 0
    reg_lambda: 5
    # min_data_in_leaf: 40
    # lambda_l1: 0.0006843555600147978
    # lambda_l2: 0.0007580997348308431
    # feature_fraction: 0.4
    # bagging_fraction: 1.0
    # bagging_freq: 0
    # min_child_samples: 20
  fit_params:
    early_stopping_rounds: 500
    verbose: 100
