hydra:
  run:
    dir: ./outputs/tmp/${now:%Y%m%d_%H%M%S}
save_dir: ./outputs/lgbm/${now:%Y%m%d_%H%M%S}
current_time: ${now:%Y%m%d_%H%M%S}
feature_names:
  - goal
  - label_encode
  - count_encode
  - by_country
  - by_category1
  - by_category2
  - html_tag_all_count
  - bins
  - goal_cross_duration
  - raw_text_features
  - remove_html_text_features
  - diff_text_features
  - raw_tfidf_sdv64
  - removed_html_tags_tfidf_sdv64
  - only_text_tfidf_sdv64
  - aggregation_country
  - aggregation_category1
  - aggregation_category2
  - aggregation_2_features
  - aggregation_3_features
  - bert_vec
  - bert_svd_64_vec
  - html_bert_vec
  - html_bert_svd_64_vec
  - bert_reduce_max_vec
  - bert_cls_token_vec
  # - bert_svd_64_vec
  # - html_bert_svd_64_vec
  # - bert_reduce_max_vec
  # - bert_cls_token_vec
  # - html_roberta_vec
  - raw_bof_nmf64
  - aggregation_bins_duration_features
  - aggregation_bins_goal_features
  - aggregation_bins_duration_goal_features
  # - raw_tfidf_sdv32
  # - removed_html_tags_tfidf_sdv32
  # - only_text_tfidf_sdv32
drop_cols:
 - index
 - id
 - goal
 - html_content
 - country
 - category1
 - category2
 - bins_duration
 - bins_goal
category_cols:
  - LE_country
  - LE_category1
  - LE_category2
  - LE_country-category1
  - LE_country-category2
  - LE_category1-category2
  - LE_country-category1-category2
  - LE_bins_duration
  - LE_bins_goal
  - LE_bins_duration-bins_goal
target_col: state
model:
  params:
    learning_rate: 0.001
    eval_metric: F1
is_test: false
seed: 42
seeds:
  - 0